// This file is generated by `cargo run --bin generate-schema -p net-meter-control`.
// Do not edit manually.

export type Association = {
  client_id: string;
  id: string;
  load?: LoadConfig | null;
  name?: string;
  payload: PayloadProfile;
  server_id: string;
  vlan?: VlanConfig | null;
};

export type ClientDef = {
  cidr: string;
  count?: number | null;
  id: string;
  name: string;
};

export type HistogramBucket = {
  count: number;
  le_ms?: number | null;
};

export type HttpMethod = "GET" | "POST";

export type HttpPayload = ({
  h2_max_concurrent_streams?: number | null;
  method: HttpMethod;
  path: string;
  path_extra_bytes?: number | null;
  request_body_bytes?: number | null;
  response_body_bytes?: number | null;
} & {
  type: "http";
});

export type LoadConfig = {
  connect_timeout_ms?: number | null;
  num_connections?: number | null;
  ramp_down_secs?: number;
  ramp_up_secs?: number;
  response_timeout_ms?: number | null;
};

export type MetricsSnapshot = {
  active_connections: number;
  by_protocol?: Record<string, PerProtocolSnapshot>;
  bytes_rx_per_sec: number;
  bytes_rx_total: number;
  bytes_tx_per_sec: number;
  bytes_tx_total: number;
  connect_mean_ms: number;
  connect_p99_ms: number;
  connections_attempted: number;
  connections_established: number;
  connections_failed: number;
  connections_timed_out: number;
  cps: number;
  is_ramping_up?: boolean;
  latency_histogram: Array<HistogramBucket>;
  latency_max_ms: number;
  latency_mean_ms: number;
  latency_p50_ms: number;
  latency_p95_ms: number;
  latency_p99_ms: number;
  requests_total: number;
  responses_total: number;
  rps: number;
  server_bytes_rx: number;
  server_bytes_tx: number;
  server_requests: number;
  status_2xx: number;
  status_4xx: number;
  status_5xx: number;
  status_code_breakdown?: Record<string, number>;
  status_other: number;
  threshold_violations?: Array<string>;
  timestamp_secs: number;
  ttfb_mean_ms: number;
  ttfb_p99_ms: number;
};

export type NetworkMode = "loopback" | "namespace" | "external_port";

export type PayloadProfile = (TcpPayload & {
  type: "tcp";
}) | (HttpPayload & {
  type: "http";
});

export type PerProtocolSnapshot = {
  active_connections: number;
  bytes_rx_total: number;
  bytes_tx_total: number;
  connections_attempted: number;
  connections_established: number;
  connections_failed: number;
  connections_timed_out: number;
  latency_mean_ms: number;
  latency_p99_ms: number;
  requests_total: number;
  responses_total: number;
  status_2xx: number;
  status_4xx: number;
  status_5xx: number;
};

export type Protocol = "tcp" | "http1" | "http2";

export type RuntimeConfig = {
  lower_iface: string;
  mode: NetworkMode;
  upper_iface: string;
};

export type ServerDef = {
  id: string;
  ip?: string | null;
  name: string;
  port: number;
  protocol: Protocol;
  tls?: boolean;
  tls_server_name?: string;
};

export type TcpOptions = {
  tcp_quickack?: boolean;
};

export type TcpPayload = ({
  rx_bytes?: number;
  tx_bytes?: number;
} & {
  type: "tcp";
});

export type TestConfig = {
  associations: Array<Association>;
  clients: Array<ClientDef>;
  default_load: LoadConfig;
  duration_secs: number;
  id: string;
  name: string;
  servers: Array<ServerDef>;
  tcp_options?: TcpOptions;
  test_type: TestType;
  thresholds?: Thresholds;
};

export type TestEventType = {
  config_name: string;
  duration_secs: number;
  test_type: string;
  type: "test_started";
} | {
  reason: string;
  type: "test_stopped";
} | {
  ramp_up_secs: number;
  type: "ramp_up_started";
} | {
  type: "ramp_up_complete";
} | {
  ramp_down_secs: number;
  type: "ramp_down_started";
} | {
  type: "ramp_down_complete";
} | {
  type: "ns_setup_complete";
} | {
  type: "ns_teardown_complete";
} | {
  type: "ext_port_setup_complete";
} | {
  type: "ext_port_teardown_complete";
} | {
  type: "threshold_violation";
  violations: Array<string>;
} | {
  message: string;
  type: "error";
};

export type TestResult = {
  config: TestConfig;
  elapsed_secs: number;
  ended_at_secs: number;
  final_snapshot: MetricsSnapshot;
  id: string;
  started_at_secs: number;
};

export type TestState = "idle" | "preparing" | "ramping_up" | "running" | "ramping_down" | "stopping" | "completed" | "failed";

export type TestStatus = {
  config?: TestConfig | null;
  elapsed_secs?: number | null;
  runtime: RuntimeConfig;
  state: TestState;
};

export type TestType = "cps" | "bw" | "cc";

export type Thresholds = {
  auto_stop_on_fail?: boolean;
  max_error_rate_pct?: number | null;
  max_latency_p99_ms?: number | null;
  min_cps?: number | null;
};

export type VlanConfig = {
  inner_vid?: number | null;
  outer_proto?: VlanProto;
  outer_vid: number;
};

export type VlanProto = "dot1_q" | "dot1_ad";

